In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [2]:
np.random.random((3,3,3))

array([[[0.42031504, 0.0574527 , 0.21053851],
        [0.35226014, 0.07918966, 0.90718312],
        [0.2039906 , 0.05367571, 0.98379623]],

       [[0.2200949 , 0.93582537, 0.29588385],
        [0.95798587, 0.08263223, 0.87753117],
        [0.10475312, 0.47981686, 0.12990999]],

       [[0.60536714, 0.52261826, 0.131022  ],
        [0.433356  , 0.25346912, 0.37671265],
        [0.86828053, 0.22131577, 0.43665555]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
def lowertriangular(a,r,c):
    for i in range(0,r):
        for j in range(0,c):
            if i <= j:
                print(0,end=' ')
            else:
                print(j+1,end=' ')
        print(' ')

a = np.zeros((5,5), dtype='int')
lowertriangular(a,5,5)

0 0 0 0 0  
1 0 0 0 0  
1 2 0 0 0  
1 2 3 0 0  
1 2 3 4 0  


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
a = np.zeros((8,8), dtype='int')
print('CheckBoard Pattern:')
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

CheckBoard Pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
arr = np.random.random((5,5))
newarr = arr.reshape(-1)
print(arr,'\n')
print(newarr)

[[0.99052548 0.74279025 0.31480759 0.51191824 0.21869112]
 [0.8769114  0.07369352 0.39535261 0.1543532  0.28156476]
 [0.90058252 0.87267055 0.50930924 0.28555914 0.98883165]
 [0.28512882 0.21932518 0.69830756 0.01216022 0.34356764]
 [0.58168089 0.62927253 0.78686649 0.60390957 0.19015504]] 

[0.99052548 0.74279025 0.31480759 0.51191824 0.21869112 0.8769114
 0.07369352 0.39535261 0.1543532  0.28156476 0.90058252 0.87267055
 0.50930924 0.28555914 0.98883165 0.28512882 0.21932518 0.69830756
 0.01216022 0.34356764 0.58168089 0.62927253 0.78686649 0.60390957
 0.19015504]


# 5.  How to find common values between two arrays?

In [6]:
a = np.array([1,2,3,4,5])
b = np.array([3,5,6,7,8])
print(a,b)
for i in a:
    if i in b:
        print(i)

[1 2 3 4 5] [3 5 6 7 8]
3
5


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
print('Yesterday:',yesterday)
today = np.datetime64('today','D')
print('Today:',today)
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print('Tomorrow:',tomorrow)

Yesterday: 2020-07-26
Today: 2020-07-27
Tomorrow: 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [8]:
A = np.random.randint(0,4,6)
B = np.random.randint(0,4,6)
print(A)
print(B)
if np.allclose(A,B):
    print('Arrays are equal')
else:
    print('Arrays are not equal')

[3 0 2 3 0 2]
[1 2 0 1 1 2]
Arrays are not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
v = np.random.random((10))
print(v)
print('\n')
print('Max value:',np.amax(v),'\n')
v[np.argmax(v)] = 0.0
print(v)

[0.6139216  0.09978521 0.3599733  0.05767051 0.93888644 0.64404106
 0.85606147 0.26670138 0.63012777 0.13388625]


Max value: 0.9388864446823619 

[0.6139216  0.09978521 0.3599733  0.05767051 0.         0.64404106
 0.85606147 0.26670138 0.63012777 0.13388625]


# 9. How to print all the values of an array?

In [10]:
a = np.random.random((6))
print(a)
print('All values of array')
for i in a:
    print(i)

[0.89986058 0.26881427 0.95952754 0.56023879 0.5476764  0.31358003]
All values of array
0.8998605841279035
0.26881427101820243
0.959527544088841
0.5602387916661558
0.5476764014744868
0.31358002646111627


# 10.Subtract the mean of each row of a matrix

In [11]:
a = np.random.random((4,4))
print(a)
print('Mean of each row')
for i in a:
    print(np.mean(i))

[[0.32569982 0.28007511 0.0209747  0.05529265]
 [0.29303589 0.28885252 0.79037437 0.3400421 ]
 [0.96335943 0.22471617 0.11689694 0.8577447 ]
 [0.26671497 0.80985114 0.63775759 0.44463851]]
Mean of each row
0.1705105687902746
0.4280762233542721
0.540679308647245
0.5397405538974579


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
a = np.random.randint(1,8,8)
b = np.array([1,0,3,5])
print(a)
print(b)
c = a[b] + 1
print('After adding 1 to each element indexed by second:')
print(c)

[5 1 7 1 4 2 5 6]
[1 0 3 5]
After adding 1 to each element indexed by second:
[2 6 2 3]


# 12.How to get the diagonal of a dot product?

In [13]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
c = np.dot(a,b)
d = np.diag(np.dot(a,b))
print(c)
print('Diagonal of above product:',d)

[[37 40]
 [85 92]]
Diagonal of above product: [37 92]


# 13.How to find the most frequent value in an array?

In [14]:
a = np.array((1,2,3,4,5,3,2,5,3,3,4))
print(np.bincount(a).argmax())

3


# 14.How to get the n largest values of an array

In [15]:
a = np.random.random(10)
np.random.shuffle(a)
print(a[np.argsort(a)])
print('Largest value of an array:')
print(a[np.argsort(a)[-1:]])

[0.02725739 0.35669639 0.36139132 0.42196048 0.42950743 0.51344348
 0.800624   0.91319111 0.91414776 0.98582749]
Largest value of an array:
[0.98582749]


# 15.How to create a record array from a regular array?

In [16]:
a = np.array([(1,2.0),(4,5.0)], dtype=[('x','int'),('y','float')])
print('Regular array',a)
a = a.view(np.recarray)
print('Record array')
print(a.x)
print(a.y)

Regular array [(1, 2.) (4, 5.)]
Record array
[1 4]
[2. 5.]
