In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import neighbors
from sklearn.metrics import *

In [2]:
df = pd.read_csv('train.csv')
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [3]:
df = df.drop(['PassengerId','Name','Ticket','Cabin'],axis=1)

In [4]:
le = preprocessing.LabelEncoder()

In [5]:
df['Sex'] = le.fit_transform(df['Sex'])

In [6]:
df['Embarked'] = le.fit_transform(df['Embarked'])

In [7]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  889 non-null    int64  
 1   Pclass    889 non-null    int64  
 2   Sex       889 non-null    int32  
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64  
 5   Parch     889 non-null    int64  
 6   Fare      889 non-null    float64
 7   Embarked  889 non-null    int32  
dtypes: float64(2), int32(2), int64(4)
memory usage: 48.7 KB


In [9]:
def k_NN(n,X,y):
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)
    knn = neighbors.KNeighborsClassifier(n_neighbors=n)
    knn_score = knn.fit(X_train,y_train).score(X_test,y_test)
    y_pred = knn.predict(X_test)
    cm = confusion_matrix(y_test,y_pred)
#     if knn_score > 0.80:
    print('Accuracy Score for k={} is: {}'.format(i,knn_score))
    print('Confusion Matrix for k={} is: \n {}'.format(i,cm))

### Accuracy Score and Confusion Matrix for Survived

In [10]:
X1 = df.drop(['Pclass'],axis=1)
y1 = df['Pclass']
for i in range(1,277):
    print('---------------------------------------')
    k_NN(i,X1,y1)
    print('---------------------------------------')

---------------------------------------
Accuracy Score for k=1 is: 0.8913857677902621
Confusion Matrix for k=1 is: 
 [[ 62   6   2]
 [  3  37   9]
 [  1   8 139]]
---------------------------------------
---------------------------------------
Accuracy Score for k=2 is: 0.8651685393258427
Confusion Matrix for k=2 is: 
 [[ 67   2   1]
 [  8  37   4]
 [  4  17 127]]
---------------------------------------
---------------------------------------
Accuracy Score for k=3 is: 0.8651685393258427
Confusion Matrix for k=3 is: 
 [[ 63   5   2]
 [  7  28  14]
 [  3   5 140]]
---------------------------------------
---------------------------------------
Accuracy Score for k=4 is: 0.8239700374531835
Confusion Matrix for k=4 is: 
 [[ 61   7   2]
 [  8  30  11]
 [  4  15 129]]
---------------------------------------
---------------------------------------
Accuracy Score for k=5 is: 0.8314606741573034
Confusion Matrix for k=5 is: 
 [[ 58  10   2]
 [  7  28  14]
 [  3   9 136]]
-------------------------

Accuracy Score for k=47 is: 0.7752808988764045
Confusion Matrix for k=47 is: 
 [[ 61   6   3]
 [  7  17  25]
 [  7  12 129]]
---------------------------------------
---------------------------------------
Accuracy Score for k=48 is: 0.7752808988764045
Confusion Matrix for k=48 is: 
 [[ 61   6   3]
 [  7  17  25]
 [  7  12 129]]
---------------------------------------
---------------------------------------
Accuracy Score for k=49 is: 0.7752808988764045
Confusion Matrix for k=49 is: 
 [[ 62   6   2]
 [  7  16  26]
 [  7  12 129]]
---------------------------------------
---------------------------------------
Accuracy Score for k=50 is: 0.7715355805243446
Confusion Matrix for k=50 is: 
 [[ 61   7   2]
 [  7  16  26]
 [  7  12 129]]
---------------------------------------
---------------------------------------
Accuracy Score for k=51 is: 0.7715355805243446
Confusion Matrix for k=51 is: 
 [[ 61   6   3]
 [  7  14  28]
 [  5  12 131]]
---------------------------------------
---------------

Accuracy Score for k=93 is: 0.7528089887640449
Confusion Matrix for k=93 is: 
 [[ 54   6  10]
 [  5  10  34]
 [  5   6 137]]
---------------------------------------
---------------------------------------
Accuracy Score for k=94 is: 0.7528089887640449
Confusion Matrix for k=94 is: 
 [[ 54   5  11]
 [  5  10  34]
 [  5   6 137]]
---------------------------------------
---------------------------------------
Accuracy Score for k=95 is: 0.7528089887640449
Confusion Matrix for k=95 is: 
 [[ 54   6  10]
 [  5  10  34]
 [  5   6 137]]
---------------------------------------
---------------------------------------
Accuracy Score for k=96 is: 0.7565543071161048
Confusion Matrix for k=96 is: 
 [[ 55   4  11]
 [  5  10  34]
 [  5   6 137]]
---------------------------------------
---------------------------------------
Accuracy Score for k=97 is: 0.7453183520599251
Confusion Matrix for k=97 is: 
 [[ 53   6  11]
 [  5  10  34]
 [  5   7 136]]
---------------------------------------
---------------

Accuracy Score for k=138 is: 0.7602996254681648
Confusion Matrix for k=138 is: 
 [[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
---------------------------------------
---------------------------------------
Accuracy Score for k=139 is: 0.7602996254681648
Confusion Matrix for k=139 is: 
 [[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
---------------------------------------
---------------------------------------
Accuracy Score for k=140 is: 0.7602996254681648
Confusion Matrix for k=140 is: 
 [[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
---------------------------------------
---------------------------------------
Accuracy Score for k=141 is: 0.7602996254681648
Confusion Matrix for k=141 is: 
 [[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
---------------------------------------
---------------------------------------
Accuracy Score for k=142 is: 0.7565543071161048
Confusion Matrix for k=142 is: 
 [[ 52  13   5]
 [  5  11  33]
 [  5   4 139]]
---------------------------------------
-----

Accuracy Score for k=182 is: 0.7565543071161048
Confusion Matrix for k=182 is: 
 [[ 52   5  13]
 [  5   7  37]
 [  5   0 143]]
---------------------------------------
---------------------------------------
Accuracy Score for k=183 is: 0.7565543071161048
Confusion Matrix for k=183 is: 
 [[ 52   5  13]
 [  5   7  37]
 [  5   0 143]]
---------------------------------------
---------------------------------------
Accuracy Score for k=184 is: 0.7528089887640449
Confusion Matrix for k=184 is: 
 [[ 51   5  14]
 [  5   7  37]
 [  5   0 143]]
---------------------------------------
---------------------------------------
Accuracy Score for k=185 is: 0.7528089887640449
Confusion Matrix for k=185 is: 
 [[ 51   5  14]
 [  5   7  37]
 [  5   0 143]]
---------------------------------------
---------------------------------------
Accuracy Score for k=186 is: 0.7490636704119851
Confusion Matrix for k=186 is: 
 [[ 51   5  14]
 [  5   6  38]
 [  5   0 143]]
---------------------------------------
-----

Accuracy Score for k=222 is: 0.7228464419475655
Confusion Matrix for k=222 is: 
 [[ 48   2  20]
 [  4   2  43]
 [  5   0 143]]
---------------------------------------
---------------------------------------
Accuracy Score for k=223 is: 0.7228464419475655
Confusion Matrix for k=223 is: 
 [[ 48   2  20]
 [  4   2  43]
 [  5   0 143]]
---------------------------------------
---------------------------------------
Accuracy Score for k=224 is: 0.7228464419475655
Confusion Matrix for k=224 is: 
 [[ 48   2  20]
 [  4   2  43]
 [  5   0 143]]
---------------------------------------
---------------------------------------
Accuracy Score for k=225 is: 0.7228464419475655
Confusion Matrix for k=225 is: 
 [[ 48   2  20]
 [  4   2  43]
 [  5   0 143]]
---------------------------------------
---------------------------------------
Accuracy Score for k=226 is: 0.7228464419475655
Confusion Matrix for k=226 is: 
 [[ 48   2  20]
 [  4   2  43]
 [  5   0 143]]
---------------------------------------
-----

Accuracy Score for k=262 is: 0.7191011235955056
Confusion Matrix for k=262 is: 
 [[ 48   0  22]
 [  4   1  44]
 [  5   0 143]]
---------------------------------------
---------------------------------------
Accuracy Score for k=263 is: 0.7191011235955056
Confusion Matrix for k=263 is: 
 [[ 48   0  22]
 [  4   1  44]
 [  5   0 143]]
---------------------------------------
---------------------------------------
Accuracy Score for k=264 is: 0.7191011235955056
Confusion Matrix for k=264 is: 
 [[ 48   0  22]
 [  4   1  44]
 [  5   0 143]]
---------------------------------------
---------------------------------------
Accuracy Score for k=265 is: 0.7191011235955056
Confusion Matrix for k=265 is: 
 [[ 48   0  22]
 [  4   1  44]
 [  5   0 143]]
---------------------------------------
---------------------------------------
Accuracy Score for k=266 is: 0.7153558052434457
Confusion Matrix for k=266 is: 
 [[ 47   0  23]
 [  4   1  44]
 [  5   0 143]]
---------------------------------------
-----