In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import *
from sklearn import svm

In [2]:
df = pd.read_csv('train.csv')
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [3]:
df = df.drop(['PassengerId','Name','Ticket','Cabin'],axis=1)

In [4]:
le = preprocessing.LabelEncoder()

In [5]:
df['Sex'] = le.fit_transform(df['Sex'])

In [6]:
df['Embarked'] = le.fit_transform(df['Embarked'])

In [7]:
df.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  889 non-null    int64  
 1   Pclass    889 non-null    int64  
 2   Sex       889 non-null    int32  
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64  
 5   Parch     889 non-null    int64  
 6   Fare      889 non-null    float64
 7   Embarked  889 non-null    int32  
dtypes: float64(2), int32(2), int64(4)
memory usage: 48.7 KB


In [12]:
def SVM(DV):
    X = df.drop([DV],axis=1)
    y = df[DV]
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)
    clf = svm.SVC(gamma=0.01,C=100)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    ac = accuracy_score(y_test,y_pred,normalize=True)
    cm = confusion_matrix(y_test,y_pred)
    print('Accuracy Score for {} is: {}'.format(DV,ac))
    print('Confusion Matrix for {} is: \n {}'.format(DV,cm))

In [13]:
Target_Variable = ['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked']

In [14]:
for i in Target_Variable:
    print('-------------------------------')
    SVM(i)
    print('-------------------------------')

-------------------------------
Accuracy Score for Survived is: 0.7415730337078652
Confusion Matrix for Survived is: 
 [[124  33]
 [ 36  74]]
-------------------------------
-------------------------------
Accuracy Score for Pclass is: 0.9026217228464419
Confusion Matrix for Pclass is: 
 [[ 64   4   2]
 [  4  36   9]
 [  1   6 141]]
-------------------------------
-------------------------------
Accuracy Score for Sex is: 0.7265917602996255
Confusion Matrix for Sex is: 
 [[ 66  32]
 [ 41 128]]
-------------------------------
-------------------------------
Accuracy Score for SibSp is: 0.7490636704119851
Confusion Matrix for SibSp is: 
 [[150  24   7   0   1   0   0]
 [ 21  39   5   0   0   0   0]
 [  4   1   3   0   0   0   0]
 [  0   2   1   3   1   0   0]
 [  0   0   0   0   2   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]]
-------------------------------
-------------------------------
Accuracy Score for Parch is: 0.797752808988764
Confusion Matrix for Parch 